### ISSUE TITLE
Research technical to build source releases

### ISSUE THREAD

**Issue by nhanntdl** [nhanntdl/PSTL#2]
Dear @all,

Here is some keyword to research for the releases milestone:
* Redirect to another page javascript.
* Include a HTML file into a HTML file.
After research, please implement what you have learned into your source

Thanks,
TrungNhan

CC: @Huong111 

Dear @Huong111 ,

Please help me review the result of this task for all members.

Thanks,
TrungNhan

**Comment by LieuTran287** [comment]
Dear @ALL,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @Huong111 ,

I had completed this work on 09/07/2020.
Spent time: 3h
Please check my work in [link](https://github.com/nhanntdl/PSTL/tree/includeHTML).

Thanks,
Lieu

**Comment by chinhminh2025** [comment]
I just done this work.
Spent time: 1h
Please check my work in [here](https://github.com/nhanntdl/PSTL/tree/Chinh)

Thanks,
Chinh
